#title in header
title: "Hi Dear."

#main info
#owner
owner: "I am zidan"
email: danielcheung41@gmail.com
info: "A web developer from China ğŸ‡¨ğŸ‡³"
#description
desc: " ğŸ’»  ğŸ¬  ğŸ± ğŸ€ ğŸš"

#menu
menu:
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Guangzhou
placelink: https://en.wikipedia.org/wiki/Guangzhou
github: https://github.com/zidanDirk
twitter: https://twitter.com/CheungDanile
juejin: https://juejin.cn/user/1275089217142663
aliyun: https://developer.aliyun.com/profile/expert/tmztehqynqvm6

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: https-adisaktijrs-github-io
